name: dart_js_interop

environment:
  sdk: ">=2.0.0-dev.63.0 <3.0.0"

dependencies:
  js: 0.6.1

dev_dependencies:
  build_runner: ^0.8.10
  build_test: ^0.10.2+5
  build_web_compilers: ^0.4.0+4
  test: ^1.0.0
